In [25]:
import pandas as pd
import seaborn as sn

In [26]:
df = pd.read_csv("../data/clean_properties.tsv", sep='\t')

In [27]:
df.property_type.unique()

array(['house', 'apartment-block', 'villa', 'mixed-use-building',
       'mansion', 'town-house', 'bungalow', 'farmhouse',
       'exceptional-property', 'country-cottage', 'manor-house',
       'apartment', 'chalet', 'other-property', 'castle', 'penthouse',
       'service-flat', 'flat-studio', 'duplex', 'triplex', 'ground-floor',
       'kot', 'loft'], dtype=object)

In [28]:
df['kitchen type'].unique()

array([nan,  3.,  0.,  1.,  2.])

In [29]:
df

,url,property_type,city,price,bedrooms,online,living area,plot surface,kitchen type,terrace surface,furnished,garden surface,swimming pool,number of frontages,building condition,how many fireplaces?
0,https://www.immoweb.be/en/classified/house/for...,house,Leke,175000.0,3.0,False,NaN,205.0,NaN,NaN,NaN,NaN,NaN,3.0,good,NaN
1,https://www.immoweb.be/en/classified/house/for...,house,Grand-halleux,299000.0,4.0,False,180.0,588.0,3.0,NaN,NaN,NaN,NaN,4.0,to be done up,1.0
2,https://www.immoweb.be/en/classified/house/for...,house,Brugge,270000.0,3.0,False,NaN,235.0,NaN,1.0,0.0,1.0,NaN,2.0,NaN,NaN
3,https://www.immoweb.be/en/classified/house/for...,house,Gosselies,299000.0,2.0,False,120.0,724.0,0.0,NaN,0.0,NaN,NaN,3.0,good,NaN
4,https://www.immoweb.be/en/classified/house/for...,house,Schaerbeek,565000.0,4.0,False,185.0,235.0,1.0,20.0,0.0,NaN,NaN,2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18788,https://www.immoweb.be/en/classified/apartment...,apartment,Anderlecht,230000.0,2.0,False,73.0,NaN,3.0,6.0,0.0,NaN,0.0,2.0,as new,NaN
18789,https://www.immoweb.be/en/classified/loft/for-...,loft,Wasseiges,290000.0,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18790,https://www.immoweb.be/en/classified/apartment...,apartment,Deerlijk,265000.0,2.0,False,84.0,NaN,3.0,11.0,0.0,NaN,0.0,NaN,NaN,NaN
18791,https://www.immoweb.be/en/classified/duplex/fo...,duplex,Aubange,190000.0,3.0,False,130.0,NaN,2.0,NaN,0.0,NaN,0.0,2.0,good,1.0
18792,https://www.immoweb.be/en/classified/apartment...,apartment,Blankenberge,215000.0,1.0,False,62.0,NaN,1.0,2.0,0.0,NaN,NaN,2.0,NaN,NaN